#!/usr/bin/env python3
"""FND-07 accepted-source custody. Default is read-only; no network acquisition.

--materialize creates one fresh run; --verify checks an existing successful run.
All Git checkout/build filters and hooks are disabled. Run materialization through
build-support/postgis/offline_exec.py to retain kernel network-denial evidence.
This is source recovery, not compilation, release or public-branch promotion.
"""
from __future__ import annotations
import argparse
from datetime import datetime, timezone
import importlib.util
import json
import os
from pathlib import Path
import sys

sys.dont_write_bytecode = True
PLATFORM = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PLATFORM/'build-support/source_restore'))
_spec=importlib.util.spec_from_file_location('ambisgis_source_custody_primitives',PLATFORM/'build-support/source_restore/common.py')
_custody=importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_custody)
for _name in ('require','sha','save','confined','fresh','verified_file','git','bundle_header','independent','restore_bundle','audit_assets'):
    globals()[_name]=getattr(_custody,_name)

MANIFEST_SHA256 = '0d7a61818d73ad27135f9bb0756797bd2c4f7e10c717d3536517534eca57cf99'
PRODUCT_BRANCH = 'ambisgis/review/fnd-07-baseline-v4'


def inputs(workspace):
    require(sha(PLATFORM/'plan/candidates/fnd-02-candidate.json') == MANIFEST_SHA256,
            'Accepted candidate bytes changed')
    candidate = json.loads((PLATFORM/'plan/candidates/fnd-02-candidate.json').read_text())
    from validate_candidate import validate_acceptance
    validate_acceptance(PLATFORM/'plan/verification/fnd-02-owner-acceptance/acceptance.json',
                        PLATFORM/'plan/candidates/fnd-02-candidate.json',candidate,PLATFORM)
    acquisition_record = next(x for x in candidate['records'] if x['id'] == 'source-acquisition')
    acquisition = json.loads(verified_file(PLATFORM, acquisition_record['location']['path'],
                                         acquisition_record['sha256'], acquisition_record['bytes']).read_text())
    approved = json.loads((PLATFORM/'plan/repositories.json').read_text())
    require({x['repository'].removeprefix('aloerch/') for x in candidate['roots']} ==
            {x['name'] for x in approved['repositories'] if x['kind']=='fork'}, 'Wrong core repository set')
    rows = []
    for root in candidate['roots']:
        custody = next(x for x in acquisition['repositories'] if x['repository']==root['repository'])
        require(custody['repository_id']==root['repository_id'], 'Wrong repository identity')
        archive = custody['archive']
        path = verified_file(workspace, archive['workspace_relative_path'],archive['sha256'],archive['size_bytes'])
        header = bundle_header(path)
        require(not header['prerequisites'], 'Initial core bundle is not self-contained')
        if root.get('tag'):
            require(header['refs'].get('refs/tags/'+root['tag'])==root.get('tag_object',root['commit']),
                    'Wrong selected source tag')
        rows.append({'root':root,'bundle':str(path),'bundle_sha256':archive['sha256'],
                     'bundle_bytes':archive['size_bytes'],'bundle_header':header})
    platform = json.loads((PLATFORM/'plan/verification/source-baseline-restore/platform-custody.json').read_text())
    verified_file(workspace,platform['path'],platform['sha256'],platform['bytes'])
    return candidate, rows, platform


def network_denied():
    import socket
    import errno
    for family in (socket.AF_INET,socket.AF_INET6):
        try:
            s=socket.socket(family,socket.SOCK_STREAM)
        except OSError as exc:
            require(exc.errno==errno.EPERM, 'Unexpected networking failure')
        else:
            s.close();raise ValueError('Materialization requires inherited upstream socket denial')


def commit_baseline(repo, root, *, gitlink=None):
    if gitlink:
        # The nested editable source is independently restored below; bind this
        # parent product commit to its actual modified source, not the donor tip.
        git(repo,'update-index','--cacheinfo','160000,'+gitlink['commit']+','+gitlink['path'])
    git(repo,'add','--all')
    if gitlink:
        git(repo,'update-index','--cacheinfo','160000,'+gitlink['commit']+','+gitlink['path'])
    changed=git(repo,'diff','--cached','--name-status').decode()
    if changed:
        git(repo,'-c','user.name=AmbisGIS source recovery','-c','user.email=source-recovery@ambisgis.invalid',
            '-c','commit.gpgsign=false','commit','-m',
            'Materialize accepted revision 4 source for '+root['id']+'\n\nGenerated by the FND-07 recovery recipe at execution time. Original history and rights retained; no release or public promotion approval.')
    commit=git(repo,'rev-parse','HEAD').decode().strip()
    git(repo,'update-ref','refs/heads/'+PRODUCT_BRANCH,commit,'0'*40)
    git(repo,'merge-base','--is-ancestor',root['commit'],commit)
    return {'commit':commit,'tree':git(repo,'rev-parse','HEAD^{tree}').decode().strip(),
            'base_commit':root['commit'],'base_tree':git(repo,'rev-parse',root['commit']+'^{tree}').decode().strip(),
            'local_branch':PRODUCT_BRANCH,'changed_paths':changed.splitlines(),
            'commit_metadata':git(repo,'show','-s','--format=fuller',commit).decode(),
            'notice_policy':'Original notices remain governed by original terms; custody grants no copyright reassignment.'}


def receipt_identity(candidate, receipt):
    expected={r['id']:r for r in candidate['roots']}
    actual={r['id']:r for r in receipt['roots']}
    require(len(actual)==len(receipt['roots']) and actual.keys()==expected.keys(),
            'Recovery receipt must cover every selected core exactly once')
    for key, root in actual.items():
        selected=expected[key]
        require(root['repository']==selected['repository'] and root['repository_id']==selected['repository_id']
                and root['base_commit']==selected['commit'] and root['relative_path']=='repos/'+key,
                'Recovery identity differs from accepted source: '+key)
    return expected


def verify_run(workspace, run, receipt_name='recovery.json'):
    receipt=json.loads(confined(run,receipt_name).read_text())
    require(sha(PLATFORM/'plan/candidates/fnd-02-candidate.json')==MANIFEST_SHA256,'Accepted selection changed')
    candidate=json.loads((PLATFORM/'plan/candidates/fnd-02-candidate.json').read_text())
    expected=receipt_identity(candidate,receipt)
    require(receipt['candidate_sha256']==MANIFEST_SHA256,'Receipt selection mismatch')
    require(sha(confined(run,'recipes.json'))==receipt['recipes_sha256'],'Recipe evidence changed')
    platform=confined(run,'platform'); independent(platform)
    require(git(platform,'rev-parse','HEAD').decode().strip()==receipt['platform_input']['commit'],'Platform revision changed')
    require(git(platform,'rev-parse','HEAD^{tree}').decode().strip()==receipt['platform_tree'],'Platform tree changed')
    require(not git(platform,'status','--porcelain','--untracked-files=all').strip(),'Platform recipes modified')
    git(platform,'fsck','--full','--no-reflogs')
    for root in receipt['roots']:
        repo=confined(run,root['relative_path']); independent(repo)
        require(git(repo,'rev-parse','HEAD').decode().strip()==root['commit'],'Restored revision changed')
        require(git(repo,'rev-parse','HEAD^{tree}').decode().strip()==root['tree'],'Restored tree changed')
        require(git(repo,'rev-parse','refs/heads/'+PRODUCT_BRANCH).decode().strip()==root['commit'],'Product review ref changed')
        git(repo,'merge-base','--is-ancestor',expected[root['id']]['commit'],root['commit'])
        assets=audit_assets(repo)
        old_notices={x['path']:x['oid'] for x in root['assets']['notice_paths']}
        new_notices={x['path']:x['oid'] for x in assets['notice_paths']}
        require(all(new_notices.get(p)==oid for p,oid in old_notices.items()),'Original notice changed or missing')
        required_links=[(x['gitlink']['path'],next(r['commit'] for r in receipt['roots'] if r['id']==x['id'])) for x in expected.values() if x.get('gitlink',{}).get('root_id')==root['id']]
        require([(x['path'],x['oid']) for x in assets['gitlinks']]==required_links,'Product gitlink changed')
        for rel,commit in required_links:
            nested=confined(repo,rel);independent(nested)
            require(git(nested,'rev-parse','HEAD').decode().strip()==commit,'Nested source revision changed')
            require(not git(nested,'status','--porcelain','--untracked-files=all').strip(),'Nested source changed')
        require(not git(repo,'status','--porcelain','--untracked-files=all').strip(),'Recovered source modified')
        git(repo,'fsck','--full','--no-reflogs')
        for entry in root['assets']['gitlinks']:
            nested=confined(repo,entry['path']); independent(nested)
            git(nested,'fsck','--full','--no-reflogs')
        for record in root.get('retained_product_bundles',[]):
            bundle=verified_file(run,record['path'],record['sha256'],record['bytes'])
            git(repo,'bundle','verify',str(bundle))
    actual={p.relative_to(run).as_posix() for d in (run/'derived',run/'product-bundles') for p in d.rglob('*') if p.is_file() or p.is_symlink()}
    require(actual=={r['path'] for r in receipt['recovered_files']},'Recovered asset membership changed')
    for record in receipt.get('executed_tooling',[]):
        verified_file(run,record['path'],record['sha256'],record['bytes'])
    for record in receipt['recovered_files']:
        verified_file(run,record['path'],record['sha256'],record['bytes'])
    corrections=verify_generated_metadata(run,receipt,candidate)
    return {'verified':True,'roots':len(receipt['roots']),'candidate_sha256':MANIFEST_SHA256,
            'scope':receipt['scope'],'remaining_blockers':receipt['remaining_blockers'],
            'historical_metadata_corrections':corrections}


def verify_generated_metadata(run, receipt, candidate):
    recipes=json.loads(confined(run,'recipes.json').read_text())
    record=next(r for r in candidate['records'] if r['id']=='qgis-generated-source')
    evidence=verified_file(run,'derived/evidence/qgis-generated-source.json',record['sha256'],record.get('bytes'))
    expected=json.loads(evidence.read_text())['added'][0]
    generated=recipes['qgis']['generated']
    require(generated['path']=='generated/qgis/'+expected['path'],'Generated file identity changed')
    artifact=verified_file(run,'derived/'+generated['path'],expected['sha256'],expected['bytes'])
    require(len(json.loads(artifact.read_text()))==generated['records'],'Generated record count changed')
    if generated['sha256']==expected['sha256']:
        return []
    correction_path=PLATFORM/'plan/verification/source-baseline-restore/qgis-receipt-correction.json'
    correction=json.loads(correction_path.read_text())
    require(correction['original_recipe_receipt_sha256']==receipt['recipes_sha256'] and
            correction['json_pointer']=='/qgis/generated/sha256' and
            correction['recorded_sha256']==generated['sha256'] and
            correction['correct_sha256']==expected['sha256'], 'Unexplained generated metadata mismatch')
    return [{'record':str(correction_path.relative_to(PLATFORM)),'sha256':sha(correction_path),
             'source_bytes_match_accepted_input':True,'historical_receipts_unchanged':True}]


def retain_tooling(run):
    tooling=run/'tooling';tooling.mkdir()
    sources=[Path(__file__),PLATFORM/'build-support/source_restore/common.py',PLATFORM/'build-support/source_restore/recipes.py']
    records=[]
    for source in sources:
        target=tooling/source.name
        with target.open('xb') as stream:stream.write(source.read_bytes())
        records.append({'source':str(source.relative_to(PLATFORM)),'path':target.relative_to(run).as_posix(),'sha256':sha(target),'bytes':target.stat().st_size})
    save(tooling/'inventory.json',records)
    return records


def materialize(workspace, name, rows, platform_input):
    network_denied()
    task=confined(workspace,'build-worktrees/source-baseline-restore')
    run=fresh(task,name)
    executed_tooling=retain_tooling(run)
    save(run/'started.json',{'started_at':datetime.now(timezone.utc).isoformat(),
                            'candidate_sha256':MANIFEST_SHA256,'status':'incomplete'})
    try:
        cores=run/'repos';cores.mkdir()
        accepted=run/'platform'
        restore_bundle(workspace/platform_input['path'],accepted,platform_input['commit'])
        require(sha(accepted/'plan/candidates/fnd-02-candidate.json')==MANIFEST_SHA256,'Restored platform selection mismatch')
        repos={};reports=[]
        for row in rows:
            root=row['root'];repo=cores/root['id']
            print('Restoring '+root['id'],flush=True)
            restore_bundle(Path(row['bundle']),repo,root['commit'],row['bundle_header']['refs'])
            if root.get('tag'):
                require(git(repo,'rev-parse','refs/custody/tags/'+root['tag']+'^{commit}').decode().strip()==root['commit'],'Peeled tag mismatch')
            assets=audit_assets(repo)
            expected=[x['root']['gitlink'] for x in rows if x['root'].get('gitlink',{}).get('root_id')==root['id']]
            require([(x['path'],x['oid']) for x in assets['gitlinks']]==[(x['path'],x['commit']) for x in expected],
                    'Unresolved submodule source')
            repos[root['id']]=repo
            reports.append({'id':root['id'],'repository':root['repository'],'repository_id':root['repository_id'],
                            'relative_path':repo.relative_to(run).as_posix(),'archive_path':row['bundle'],
                            'archive_sha256':row['bundle_sha256'],'archive_prerequisites':[], 'assets':assets})
            save(run/(root['id']+'-base.json'),reports[-1])
        from recipes import materialize_recipes
        recipe_result=materialize_recipes(accepted,workspace,repos,run/'derived')
        save(run/'recipes.json',recipe_result)
        # MapStore product commit precedes the parent client's gitlink binding.
        ordered=sorted(rows,key=lambda x:x['root']['id']=='mapstore-client')
        commits={};bundles=run/'product-bundles';bundles.mkdir()
        for row in ordered:
            root=row['root'];repo=repos[root['id']]
            link=None
            child_roots=[x['root'] for x in rows if x['root'].get('gitlink',{}).get('root_id')==root['id']]
            require(len(child_roots)<=1,'Multiple nested sources require explicit handling')
            if child_roots:
                parent_link=child_roots[0]['gitlink'];child=commits[child_roots[0]['id']]
                link={'path':parent_link['path'],'commit':child['commit']}
                nested=repo/parent_link['path']
                require(nested.is_dir() and not any(nested.iterdir()),'Submodule path collision')
                nested.rmdir() # Only the freshly created, verified empty Git placeholder.
                child_bundle=bundles/'mapstore-full.bundle'
                git(repos['mapstore'],'bundle','create',str(child_bundle),'--all')
                restore_bundle(child_bundle,nested,child['commit'])
            baseline=commit_baseline(repo,root,gitlink=link);commits[root['id']]=baseline
            r=next(x for x in reports if x['id']==root['id']);r.update(baseline)
            r['retained_product_bundles']=[]
            if baseline['commit']!=root['commit']:
                delta=bundles/(root['id']+'-product.bundle')
                git(repo,'bundle','create',str(delta),'refs/heads/'+PRODUCT_BRANCH,'^'+root['commit'])
                r['retained_product_bundles'].append({'path':delta.relative_to(run).as_posix(),'sha256':sha(delta),
                    'bytes':delta.stat().st_size,'prerequisites':bundle_header(delta)['prerequisites'],
                    'required_predecessor_archive_sha256':row['bundle_sha256']})
            independent(repo)
            require(not git(repo,'status','--porcelain','--untracked-files=all').strip(),'Uncommitted source materialization')
        recovered=[]
        for directory in (run/'derived',bundles):
            for p in sorted(directory.rglob('*')):
                require(not p.is_symlink(),'Derived custody symlink not supported')
                if p.is_file():recovered.append({'path':p.relative_to(run).as_posix(),'sha256':sha(p),'bytes':p.stat().st_size})
        receipt={'schema_version':1,'candidate_sha256':MANIFEST_SHA256,
                 'finished_at':datetime.now(timezone.utc).isoformat(),'status':'source-recovery-checkpoint',
                 'scope':'Bounded T-OWN-01 source recovery; no compilation, full FND-07 acceptance, FND-08, distribution or release.',
                 'executed_tooling':executed_tooling,'platform_input':platform_input,'platform_tree':git(accepted,'rev-parse','HEAD^{tree}').decode().strip(),
                 'roots':reports,'recipes_sha256':sha(run/'recipes.json'),'recovered_files':recovered,
                 'remaining_blockers':['Remote product-source branch delivery and workflow review need separate owner approval.',
                                       'Human FND-07 source/provenance review remains pending.']+recipe_result.get('blockers',[])}
        save(run/'pending-recovery.json',receipt)
        verify_run(workspace,run,'pending-recovery.json')
        (run/'pending-recovery.json').rename(run/'recovery.json')
        print(json.dumps({'status':receipt['status'],'run':str(run),'roots':len(reports),'blockers':receipt['remaining_blockers']}))
        return receipt
    except Exception as exc:
        save(run/'failure.json',{'status':'failed','error':str(exc),'finished_at':datetime.now(timezone.utc).isoformat()})
        raise


def recover_bundle_chain(workspace, source_name, target_name, receipt_sha256):
    """Recover reviewed local product commits from archives, never old object stores."""
    network_denied()
    task=confined(workspace,'build-worktrees/source-baseline-restore')
    source=confined(task,source_name)
    previous=json.loads(verified_file(source,'recovery.json',receipt_sha256).read_text())
    candidate,rows,platform_input=inputs(workspace)
    receipt_identity(candidate,previous)
    require(previous['platform_input']==platform_input,'Wrong platform custody chain')
    require(sha(source/'recipes.json')==previous['recipes_sha256'],'Changed recipe receipt')
    selected_files={r['path']:r for r in previous['recovered_files']}
    for record in selected_files.values():
        verified_file(source,record['path'],record['sha256'],record['bytes'])
    run=fresh(task,target_name)
    executed_tooling=retain_tooling(run)
    save(run/'started.json',{'source_receipt_sha256':sha(source/'recovery.json'),
                            'started_at':datetime.now(timezone.utc).isoformat(),'status':'incomplete'})
    try:
        (run/'repos').mkdir()
        restore_bundle(workspace/platform_input['path'],run/'platform',platform_input['commit'])
        for row in rows:
            root=row['root'];prior=next(r for r in previous['roots'] if r['id']==root['id'])
            print('Recovering product archive chain '+root['id'],flush=True)
            repo=run/'repos'/root['id']
            restore_bundle(Path(row['bundle']),repo,root['commit'],row['bundle_header']['refs'])
            for delta in prior['retained_product_bundles']:
                require(delta['required_predecessor_archive_sha256']==row['bundle_sha256'],'Wrong predecessor archive')
                bundle=verified_file(source,delta['path'],delta['sha256'],delta['bytes'])
                require(bundle_header(bundle)['prerequisites']==delta['prerequisites'],'Changed prerequisite list')
                git(repo,'bundle','verify',str(bundle))
                git(repo,'bundle','unbundle',str(bundle))
            git(repo,'checkout','--detach',prior['commit'])
            git(repo,'update-ref','refs/heads/'+PRODUCT_BRANCH,prior['commit'],'0'*40)
            require(git(repo,'rev-parse','HEAD^{tree}').decode().strip()==prior['tree'],'Product archive tree mismatch')
            independent(repo)
        for root in candidate['roots']:
            if root.get('gitlink'):
                link=root['gitlink'];parent=run/'repos'/link['root_id']
                nested=confined(parent,link['path']);require(nested.is_dir() and not any(nested.iterdir()),'Nested source collision')
                nested.rmdir()
                bundle_record=selected_files['product-bundles/mapstore-full.bundle']
                bundle=verified_file(source,bundle_record['path'],bundle_record['sha256'],bundle_record['bytes'])
                product=next(r for r in previous['roots'] if r['id']==root['id'])
                restore_bundle(bundle,nested,product['commit'])
        import shutil
        for record in selected_files.values():
            target=confined(run,record['path'],exists=False);target.parent.mkdir(parents=True,exist_ok=True)
            with target.open('xb') as dst, (source/record['path']).open('rb') as src:
                shutil.copyfileobj(src,dst)
        with (run/'recipes.json').open('xb') as dst, (source/'recipes.json').open('rb') as src:
            shutil.copyfileobj(src,dst)
        receipt=dict(previous,finished_at=datetime.now(timezone.utc).isoformat(),executed_tooling=executed_tooling,
                     recovered_from_receipt_sha256=sha(source/'recovery.json'),
                     method='Independent base bundle plus verified explicit product delta predecessor chain; copied source assets verified by bytes; no source working tree used.')
        save(run/'pending-recovery.json',receipt)
        result=verify_run(workspace,run,'pending-recovery.json')
        save(run/'chain-verification.json',result)
        (run/'pending-recovery.json').rename(run/'recovery.json')
        print(json.dumps(result))
    except Exception as exc:
        # A failed verification is never left next to a success-looking final receipt.
        if (run/'recovery.json').exists():
            (run/'recovery.json').rename(run/'unverified-recovery.json')
        save(run/'failure.json',{'status':'failed','error':str(exc)})
        raise


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--workspace-root',type=Path,required=True)
    modes=parser.add_mutually_exclusive_group();modes.add_argument('--materialize',action='store_true');modes.add_argument('--verify',action='store_true');modes.add_argument('--recover-bundle-chain',action='store_true')
    parser.add_argument('--receipt-sha256',help='Required trusted receipt digest for verify or bundle-chain input')
    parser.add_argument('--from-run',help='Existing successful private custody run for bundle-chain recovery')
    parser.add_argument('--run',help='Single fresh child name beneath workspace/build-worktrees/source-baseline-restore')
    args=parser.parse_args();workspace=args.workspace_root.absolute()
    if args.recover_bundle_chain:
        require(args.from_run and args.run and '/' not in args.run and '/' not in args.from_run,'Bundle-chain recovery requires two child names')
        require(args.receipt_sha256,'Bundle-chain recovery requires trusted --receipt-sha256')
        recover_bundle_chain(workspace,args.from_run,args.run,args.receipt_sha256);return
    require(args.from_run is None,'--from-run requires --recover-bundle-chain')
    if args.verify:
        require(args.run is not None,'--verify requires --run')
        run=confined(workspace,'build-worktrees/source-baseline-restore/'+args.run)
        require(args.receipt_sha256,'Verification requires trusted --receipt-sha256')
        verified_file(run,'recovery.json',args.receipt_sha256)
        print(json.dumps(verify_run(workspace,run)));return
    require(args.receipt_sha256 is None,'--receipt-sha256 requires verify or bundle-chain recovery')
    candidate,rows,platform=inputs(workspace)
    if args.materialize:
        require(args.run is not None and '/' not in args.run,'--materialize requires one fresh child run name')
        materialize(workspace,args.run,rows,platform)
    else:
        require(args.run is None,'--run is only valid for materialize/verify')
        print(json.dumps({'mode':'read-only','candidate_sha256':MANIFEST_SHA256,
                          'roots':[{'id':x['root']['id'],'repository_id':x['root']['repository_id'],'commit':x['root']['commit'],
                                    'bundle_sha256':x['bundle_sha256'],'bundle_prerequisites':x['bundle_header']['prerequisites']} for x in rows],
                          'platform':platform,'remote_mutations':False},indent=2))

if __name__=='__main__':
    try:main()
    except (ValueError,OSError) as exc:
        print('restore_sources: '+str(exc),file=sys.stderr);sys.exit(1)
